### ISSUE TITLE
Doesn't support ISiloBuilder

### ISSUE THREAD

**Issue by hahn-kev** [OrleansContrib/Orleans.EventSourcing.Snapshot#1]
Currently the configuration extensions only support `ISiloHostBuilder` however if you're using the new dotnet core 3 `IHostBuilder` interfance with Orleans, then you only get a `ISiloBuilder` interfance to configure the silo. Can support for `ISiloBuilder` be added?

**Comment by zh6335901** [comment]
OK, I will add it in a few days

**Comment by zh6335901** [comment]
Hi, It’s supported ISiloBuilder now. You can use the lastest version package:) (sorry it’s delayed)
