### ISSUE TITLE
How does this handle grains that receive a lot of messages

### ISSUE THREAD

**Issue by zeus82** [OrleansContrib/Orleans.EventSourcing.Snapshot#2]
From what I understand, this uses the standard grain storage under the hood, so what happens if I have a very chatty grain that writes a lot of events.  Does the grain state all get stored under one grain, or does it get spread out?

**Comment by zh6335901** [comment]
You can use independent event storage(set `UseIndependentEventStorage` true), it means grain events store in a independent storage that you configured.
